### PR TITLE
use istio 1.16.0 manifests

### PR DESCRIPTION
**Pull request by k4leung4**
Signed-off-by: Kenny Leung <kleung@chainguard.dev>

# Changes

- 🎁 use istio 1.16.0 manifests

/kind cleanup

Fixes #

**Release Note**

```release-note
use istio 1.16.0 manifests
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by dprotaso** [comment]
update is flakey - oddly I don't recall retry

**Review by AngeloDanducci — APPROVED** [review]

**Pull request merged**
