### PR TITLE
Rename file to comply with divisive language

### PR DESCRIPTION
**Pull request by markusthoemmes**
Dummy is considered divisive language and the alternative is much better anyway.

/assign @nak3

### CODE REVIEW

**Review by nak3 — CHANGES_REQUESTED** [review]
Could you rename this file https://github.com/knative-sandbox/net-istio/blob/master/third_party/istio-stable/dummy.go as weell?

It is necessary for docs repo.

**Comment by markusthoemmes** [comment]
Will do, third_party is ignored by the checker by default.

/hold

**Review by nak3 — APPROVED** [review]

**Pull request merged**
