### PR TITLE
[release-0.17] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign tcnghia
/cc tcnghia

### CODE REVIEW

**Comment by tcnghia** [comment]
/hold

I am not sure if we want to cause a release just because of a vendor change in `test-infra` 
cc @nak3 @ZhiminXiang

**Comment by ZhiminXiang** [comment]
If this is the only for `test-infra` update, I think we should close this one.

**Comment by vagababov** [comment]
I have a more interesting question: why did we merge test-infra into release branch in the first place?

/cc @chizhg @chaodaiG

**Comment by chizhg** [comment]
> I have a more interesting question: why did we merge test-infra into release branch in the first place?
> 
> /cc @chizhg @chaodaiG

We started cutting release for test-infra repo since release-0.13 by following the same schedule as all other Knative repos, IIRC it was because ppl had concerns on the backward compatibility for the scripts under test-infra repo.

**Pull request closed without merging**
