### PR TITLE
Drop istio-minimal.yaml

### PR DESCRIPTION
**Pull request by nak3**
`istio-minimal.yaml (istio-local.yaml)` was introduced by https://github.com/knative/serving/pull/6025
for local deployments.
But today `istio-minimal.yaml` is equivalent to `istioctl install -y` so we
don't need to keep the manifest in the repo.

Note, current `istio-minimal.yaml` has
`TERMINATION_DRAIN_DURATION_SECONDS` but it was added to solve flake
of e2e test by https://github.com/knative-sandbox/net-istio/pull/553 so it is not mandatory.

/kind cleanup

/cc @markusthoemmes @arturenault @dprotaso

### CODE REVIEW

**Review by arturenault — DISMISSED** [review]
nice, much cleaner.

/lgtm

**Review by arturenault — APPROVED** [review]
/lgtm

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
