### PR TITLE
Cherrypick PRs necessary for compilation of release-0.21 against working istio API deps.

### PR DESCRIPTION
**Pull request by Cynocracy**
# Changes

Import changes needed for release-0.21 of net-istio to compile into a single controller with serving.

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by Cynocracy** [comment]
@googlebot I consent

**Comment by markusthoemmes** [comment]
Can you elaborate on this? Why would we do this?

**Comment by Cynocracy** [comment]
There are a few commits in main that are needed for libs to build against 0.21

(https://github.com/knative-sandbox/net-istio/pull/568 and https://github.com/knative-sandbox/net-istio/pull/569), I figured with 2 commits needed, a fast-forward of the branch was preferred to cherry-picking, but I may just be unfamiliar with the processes out here, tbh. I can just cherrypick the relevant PRs if that's preferable.

**Comment by markusthoemmes** [comment]
Which libs are we referring to here? 0.22 will be released next Tuesday, would that not be enough?

**Comment by markusthoemmes** [comment]
Other than that, yeah, please no fast-forward, just cherry-pick what you think is necessary and valuable.

**Comment by Cynocracy** [comment]
SG, sorry for the confusion on my part :)

**Comment by Cynocracy** [comment]
Updated to be just cherrypicks of the relevant ones

**Pull request closed without merging**
