### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by JRBANCEL**
Yet another breaking change: KIngress.LoadBalancer was deprecated.

/assign @ZhiminXiang 
/assign @nak3 

Will close https://github.com/knative-sandbox/net-istio/pull/272.

### CODE REVIEW

**Review by tcnghia — APPROVED** [review]
/lgtm

**Comment by tcnghia** [comment]
@JRBANCEL you may want to pick up https://github.com/knative/networking/pull/146/files

**Comment by JRBANCEL** [comment]
> @JRBANCEL you may want to pick up https://github.com/knative/networking/pull/146/files

I just picked it up. Let see if this fixes the hash mismatch in the conformance tests.

**Comment by JRBANCEL** [comment]
@tcnghia @ZhiminXiang 
Please /lgtm again 🙏

**Pull request merged**
