### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign tcnghia
/cc tcnghia

### CODE REVIEW

**Comment by vagababov** [comment]
I tried to fix this, but there's more than just renames
semantics changed this needs to be done manually
/assign @nak3

**Comment by mattmoor** [comment]
@nak3 @ZhiminXiang 

This will need to be fixed manually:
```

pkg/reconciler/ingress/resources/virtual_service.go:231:9: http.Retries undefined (type *v1alpha1.HTTPIngressPath has no field or method Retries)
pkg/reconciler/ingress/resources/virtual_service.go:234:24: http.Retries undefined (type *v1alpha1.HTTPIngressPath has no field or method Retries)
pkg/reconciler/ingress/resources/virtual_service.go:236:10: http.Retries undefined (type *v1alpha1.HTTPIngressPath has no field or method Retries)
pkg/reconciler/ingress/resources/virtual_service.go:237:58: http.Retries undefined (type *v1alpha1.HTTPIngressPath has no field or method Retries)
```

**Comment by nak3** [comment]
Thank you! 
Yes, @JRBANCEL is fixing it now in https://github.com/knative-sandbox/net-istio/pull/263

**Pull request closed without merging**
