### PR TITLE
Pin some knative.dev deps to release-0.17

### PR DESCRIPTION
**Pull request by yanweiguo**

### CODE REVIEW

**Comment by vagababov** [comment]
/hold
we want https://github.com/knative/pkg/pull/1604 to be in 0.17 — otherwise it's gonna be world of hurt with crashing e2e tests.

**Comment by vagababov** [comment]
I'll cherry pick it.

**Comment by yanweiguo** [comment]
> /hold
> we want [knative/pkg#1604](https://github.com/knative/pkg/pull/1604) to be in 0.17 — otherwise it's gonna be world of hurt with crashing e2e tests.

The pick is included now.

**Pull request merged**
