### PR TITLE
bump istio api and client-go to v1.16.0

### PR DESCRIPTION
**Pull request by k4leung4**
Signed-off-by: Kenny Leung <kleung@chainguard.dev>

# Changes

- 🧹  bump istio api and client-go to v1.16.0

/kind cleanup

Fixes #

**Release Note**

```release-note
bump istio api and client-go to v1.16.0
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by k4leung4** [comment]
@nak3 I'm blocked on getting the conformance test to pass.
Looks like the jump to 1.14.x+ breaks the conformance test and im not sure where to begin debugging.

i verified that 1.13.9 is the last version that passes the conformance tests.
https://github.com/knative-sandbox/net-istio/pull/1022

one notable change in 1.14.x is the swap to a different protobuf library, though not sure why it would cause the conformance test to fail

@tcnghia @mattmoor in case you might have some insight

**Comment by dprotaso** [comment]
cc @AngeloDanducci

**Comment by nak3** [comment]
It seems DomainMapping (HostRewrite) has an issue :thinking: 
I built the image from your tree then deploying the DomainMapping resource caused the following panic:

```
$ kubectl  -n knative-serving logs net-istio-controller-74f67c79d9-p29cc -p

panic: cannot handle unexported field at {*v1alpha3.VirtualService}.Http[0].Rewrite.state:
	"istio.io/api/networking/v1alpha3".HTTPRewrite
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported
 ...
github.com/google/go-cmp/cmp.Equal({0x1c0fbe0, 0xc000a426c0}, {0x1c0fbe0, 0xc000a429c0}, {0xc0006dfac0?, 0xc0000b370d?, 0xd?})
	github.com/google/go-cmp@v0.5.9/cmp/compare.go:95 +0x69
knative.dev/net-istio/pkg/reconciler/accessor/istio.hasDesiredDiff(0xc000c12900, 0xc000c12240)
	knative.dev/net-istio/pkg/reconciler/accessor/istio/virtualservice.go:45 +0x405
knative.dev/net-istio/pkg/reconciler/accessor/istio.ReconcileVirtualService({0x1fa3ed8, 0xc000ab84b0}, {0x1fbd7a8?, 0xc00095a480}, 0xc000c12240, {0x1f911b0, 0xc00050d680})
	knative.dev/net-istio/pkg/reconciler/accessor/istio/virtualservice.go:87 +0x1dd
knative.dev/net-istio/pkg/reconciler/ingress.(*Reconciler).reconcileVirtualServices(0xc00050d680, {0x1fa3ed8, 0xc000ab84b0}, 0xc00095a480, {0xc000692290, 0x1, 0x0?})
	knative.dev/net-istio/pkg/reconciler/ingress/ingress.go:326 +0x188
knative.dev/net-istio/pkg/reconciler/ingress.(*Reconciler).reconcileIngress(0xc00050d680, {0x1fa3ed8, 0xc000ab84b0}, 0xc00095a480)
	knative.dev/net-istio/pkg/reconciler/ingress/ingress.go:197 +0xf50
knative.dev/net-istio/pkg/reconciler/ingress.(*Reconciler).ReconcileKind(0x2?, {0x1fa3ed8, 0xc000ab84b0}, 0xc00095a480)
	knative.dev/net-istio/pkg/reconciler/ingress/ingress.go:95 +0x97
knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress.(*reconcilerImpl).Reconcile(0xc000020d10, {0x1fa3ed8, 0xc000ab83f0}, {0xc0005e62c0, 0x1f})
	knative.dev/networking@v0.0.0-20221117015040-9b791e24e63a/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go:250 +0x662
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0003ea9c0)
	knative.dev/pk
g@v0.0.0-20221117013641-f5c1a03ab4f1/controller/controller.go:542 +0x58d
knative.dev/pkg/controller.(*Impl).RunContext.func3()
	knative.dev/pkg@v0.0.0-20221117013641-f5c1a03ab4f1/controller/controller.go:491 +0x68
created by knative.dev/pkg/controller.(*Impl).RunContext
	knative.dev/pkg@v0.0.0-20221117013641-f5c1a03ab4f1/controller/controller.go:489 +0x312
``` 
I hope this helps your debugging :pray:

**Comment by nak3** [comment]
/lgtm
/assign @AngeloDanducci 
Great! Thank you!

**Comment by k4leung4** [comment]
one minor tweak.

thank you so much for your help.

**Review by AngeloDanducci — APPROVED** [review]

**Comment by AngeloDanducci** [comment]
Thanks for this contribution!

**Pull request merged**
