### PR TITLE
Use knative-local-gateway as only default Gateway.

### PR DESCRIPTION
**Pull request by JRBANCEL**
This is phase 2 of #212. 

/hold
DO NOT MERGE UNTIL 0.18 IS RELEASED.

/assign @ZhiminXiang @tcnghia

### CODE REVIEW

**Comment by tcnghia** [comment]
@JRBANCEL is this still needed?

**Comment by tcnghia** [comment]
@JRBANCEL I think this can go in now?

**Comment by JRBANCEL** [comment]
Yes, I'll do this now or tomorrow.

**Comment by JRBANCEL** [comment]
@tcnghia @ZhiminXiang this is ready

**Review by vagababov — APPROVED** [review]
/lgtm

**Pull request merged**
