### PR TITLE
use the new hack repo for scripts

### PR DESCRIPTION
**Pull request by n3wscott**
## Proposed Changes

- test-infra/scripts -> hack

ref: https://github.com/knative/hack/pull/2

### CODE REVIEW

**Comment by nak3** [comment]
It seems the `verify` is still failing https://github.com/knative-sandbox/net-istio/pull/380/checks?check_run_id=1318052611

**Comment by nak3** [comment]
@n3wscott sorry for bothering you but could you please rebase this? Otherwise, LGTM.

**Comment by n3wscott** [comment]
Omg why did no one let it merge after the last rebase?

**Pull request merged**
