### PR TITLE
chore: Migrate to sets.Set[string] when possible

### PR DESCRIPTION
**Pull request by pastequo**
# Changes

- :broom: Migrate `sets.String` to `sets.Set[string]` when possible, `sets.String` being deprecated
- Not every place could have been changed, some dependencies (internal to knative, external to this repo) are still using `sets.String`

/kind cleanup

This chnages is motivated by the linter complaining about that

### CODE REVIEW

**Comment by dprotaso** [comment]
thanks @pastequo just some minor linter stuff - see the 'Files Changed' tab

**Comment by pastequo** [comment]
Sure, I couldn't remove this one, so I put a `// nolint: staticcheck` instead

**Comment by dprotaso** [comment]
/approve

thanks @pastequo and @kauana for the review

**Pull request merged**
