### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign tcnghia
/cc tcnghia

### CODE REVIEW

**Comment by vagababov** [comment]
/assign @JRBANCEL 
JR can you finish your PR? :)

**Comment by JRBANCEL** [comment]
> /assign @JRBANCEL
> JR can you finish your PR? :)

It is done, but I found a bug in the AutoTLS unit tests in the process.
This is fixed in https://github.com/knative-sandbox/net-istio/pull/270, merging right now.
Then I'll rebase my PR on top of https://github.com/knative-sandbox/net-istio/pull/270 and it is good to go.

**Comment by JRBANCEL** [comment]
There is another breaking change and the bot doesn't seem to be able to rebase :smile:. See https://github.com/knative-sandbox/net-istio/pull/273.
/close

**Pull request closed without merging**
