### PR TITLE
Bump istio api and client from v1alpha3 to v1beta1

### LINKED ISSUE #1087: switch to Istio v1beta1 API
As per title, we are still using v1alpha3 after https://github.com/knative-sandbox/net-istio/pull/203.
We should bump the API version to v1beta1.

### PR DESCRIPTION
**Pull request by ReToCode**
## Changes
- Bump istio api and client from v1alpha3 to v1beta1

Fixes #1087

```release-note
net-istio now uses istio resources in version `v1beta1`. Please update your `Gateway` objects to `v1beta1`.
```

### CODE REVIEW

**Comment by nak3** [comment]
Thank you!
Lint complains as https://github.com/knative-sandbox/net-istio/actions/runs/4729117491/jobs/8391303655?pr=1099 though the issue should have been exist since long time ago :disappointed: 
Will you fix it in this PR or another PR?

**Comment by ReToCode** [comment]
> Will you fix it in this PR or another PR?

I think in a separate PR is cleaner: https://github.com/knative-sandbox/net-istio/pull/1100. Will rebase this one here when merged.

**Pull request merged**
