### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign tcnghia
/cc tcnghia

### CODE REVIEW

**Comment by tcnghia** [comment]
/retest

@ZhiminXiang @JRBANCEL it seems net-istio HEAD may be broken?

**Comment by JRBANCEL** [comment]
Yes, KIngress had fields removed in https://github.com/knative/networking/pull/132.
Let me fix this.

**Comment by mattmoor** [comment]
Not removed, but renamed.

**Pull request closed without merging**
