### PR TITLE
Build for all platforms

### PR DESCRIPTION
**Pull request by julz**
# Changes

- :gift: Build images for all the platforms ko supports. This matches what we already do in serving and `net-contour` as of https://github.com/knative-sandbox/net-contour/pull/285. Of course, users will still need an appropriate version of istio itself for each platform, but this makes sure knative can be deployed once those exist for a platform.

/kind enhancement

**Release Note**

```release-note
Images are now multi-platform and support architectures such as `arm64`.
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by JRBANCEL** [comment]
> architectures such as `arm64`

Planning to get a Macbook with a M1 SOC 😄 ?

/lgtm

**Comment by julz** [comment]
> Planning to get a Macbook with a M1 SOC 😄 ?

How else will we be able to test things like this? Clear business expense..

The things I do for open source........ ;)

**Comment by arturenault** [comment]
/lgtm

next stop: quantum

**Review by arturenault — APPROVED** [review]

**Review by tcnghia — APPROVED** [review]

**Pull request merged**
