### PR TITLE
Bump istio client deps version to v1.10.3

### PR DESCRIPTION
**Pull request by nak3**
This patch Bump istio client deps to v1.10.3.

There are no big change but just align with supported Istio version.

/kind cleanup
Fix https://github.com/knative-sandbox/net-istio/issues/755
/cc @ZhiminXiang @tcnghia

### CODE REVIEW

**Comment by nak3** [comment]
/retest

data race but it happens by test utils - [logs](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_net-istio/761/pull-knative-sandbox-net-istio-latest/1436130103028355072). We need to fix it in networking repo.

```
WARNING: DATA RACE
Read at 0x00c000449470 by goroutine 244:
  runtime.mapaccess1()
      /root/.gvm/gos/go1.16.4/src/runtime/map.go:394 +0x0
  crypto/x509.(*CertPool).addCertFunc()
      /root/.gvm/gos/go1.16.4/src/crypto/x509/cert_pool.go:188 +0x212
  crypto/x509.(*CertPool).AddCert()
      /root/.gvm/gos/go1.16.4/src/crypto/x509/cert_pool.go:172 +0x56
  knative.dev/networking/test/conformance/ingress.CreateTLSSecretWithCertPool()
      /home/prow/go/src/knative.dev/net-istio/vendor/knative.dev/networking/test/conformance/ingress/util.go:856 +0x8d2
  knative.dev/networking/test/conformance/ingress.CreateTLSSecret()
      /home/prow/go/src/knative.dev/net-istio/vendor/knative.dev/networking/test/conformance/ingress/util.go:809 +0x244
  knative.dev/networking/test/conformance/ingress.TestIngressTLS()
      /home/prow/go/src/knative.dev/net-istio/vendor/knative.dev/networking/test/conformance/ingress/tls.go:38 +0x1bc
  testing.tRunner()
      /root/.gvm/gos/go1.16.4/src/testing/testing.go:1193 +0x202

Previous write at 0x00c000449470 by goroutine 260:
  runtime.mapassign()
      /root/.gvm/gos/go1.16.4/src/runtime/map.go:571 +0x0
  crypto/x509.(*CertPool).addCertFunc()
      /root/.gvm/gos/go1.16.4/src/crypto/x509/cert_pool.go:192 +0x2a4
  crypto/x509.(*CertPool).AddCert()
      /root/.gvm/gos/go1.16.4/src/crypto/x509/cert_pool.go:172 +0x56
  knative.dev/networking/test/conformance/ingress.CreateTLSSecretWithCertPool()
      /home/prow/go/src/knative.dev/net-istio/vendor/knative.dev/networking/test/conformance/ingress/util.go:856 +0x8d2
  knative.dev/networking/test/conformance/ingress.CreateTLSSecret()
      /home/prow/go/src/knative.dev/net-istio/vendor/knative.dev/networking/test/conformance/ingress/util.go:809 +0x1f1
  knative.dev/networking/test/conformance/ingress.create()
      /home/prow/go/src/knative.dev/net-istio/vendor/knative.dev/networking/test/conformance/ingress/httpoption.go:67 +0x169
  knative.dev/networking/test/conformance/ingress.TestHTTPOption()
      /home/prow/go/src/knative.dev/net-istio/vendor/knative.dev/networking/test/conformance/ingress/httpoption.go:52 +0x20b
  testing.tRunner()
      /root/.gvm/gos/go1.16.4/src/testing/testing.go:1193 +0x202
```

**Review by tcnghia — APPROVED** [review]

**Comment by nak3** [comment]
/retest

The connection timeout errror:

```
=== CONT  TestIngressConformance/5/dispatch/path_and_percentage
    util.go:971: Unable to read response body: read tcp 10.4.39.16:46636->34.139.14.28:80: read: connection timed out
    util.go:971: Error dumping response: read tcp 10.4.39.16:46636->34.139.14.28:80: read: connection timed out
    util.go:971: 
    path.go:228: Error while sending requests: failed to request
```

Current net-istio's conformance is not stable since 25/Sep. The same error happens in continuous test.

https://testgrid.k8s.io/r/knative-own-testgrid/net-istio#latest
https://testgrid.k8s.io/r/knative-own-testgrid/net-istio#continuous

**Pull request merged**
