### PR TITLE
Move to Go 1.17

### PR DESCRIPTION
**Pull request by skonto**
# Changes

- Other components like net-kourier have already moved to 1.17.
- Two commits for easier review.

### CODE REVIEW

**Comment by nak3** [comment]
/lgtm
/hold

`/hold` for CI.
Just FYI, I am planning to propose this change https://github.com/knative/hack/pull/179 to make the project uses the same Go version consistently.

**Comment by skonto** [comment]
Rebased. @nak3 gentle ping.

**Comment by dprotaso** [comment]
Related issue: https://github.com/knative-sandbox/net-istio/issues/938

@AngeloDanducci this PR seems to reproduce this reliably

**Comment by AngeloDanducci** [comment]
Opened an issue related to the error we're seeing here: https://github.com/knative-sandbox/net-istio/issues/938

Seems like it may be related to something opened previously in upstream Istio.

**Pull request merged**
