### PR TITLE
Bump Istio head

### PR DESCRIPTION
**Pull request by nak3**
istio-head does not bump generated istio yaml automatically ass https://github.com/knative-sandbox/net-istio/blob/f92596ff8ae2b2a2b37def30944bb234561c91b4/hack/update-codegen.sh#L64-L66
this patch bumps istio-head manually.

/assign @dprotaso

### CODE REVIEW

**Comment by nak3** [comment]
We are testing istio-1.11 by istio-head now :fearful:

**Comment by dprotaso** [comment]
/lgtm
/approve

We should figure out how to document what version we're bumping to.

Also related - maybe we should bump to some notable pre-release and not HEAD. ie. bump to a latest nightly release on a Friday.

**Comment by nak3** [comment]
/test pull-knative-sandbox-net-istio-latest

`pull-knative-sandbox-net-istio-latest` is required=false, why it is not merged :thinking:

**Comment by nak3** [comment]
Ah, I see. @dprotaso Could you please approve via github? `/approve` does not work on knative-sandbox :sweat_smile:

**Comment by dprotaso** [comment]
There’s no CLA label which is weird

**Comment by nak3** [comment]
Hmm... Another PR also does not have the CLA label https://github.com/knative-sandbox/net-istio/pull/829

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
