### PR TITLE
Bump Istio to 1.18.0

### PR DESCRIPTION
**Pull request by nak3**
This patch bumps Istio version to 1.18.0.

It includes the change:
* Drop `replace` in go.mod
* Modify the version in `./third_party/istio-latest/generate-manifests.sh` and run `hack` scripts.

### CODE REVIEW

**Comment by nak3** [comment]
All review dog error is vendor's file `vendor/k8s.io/code-generator/generate-internal-groups.sh`.

```
Raw Output:
vendor/k8s.io/code-generator/generate-internal-groups.sh:104:-        --clientset-name "${CLIENTSET_NAME_INTERNAL:-internalversion}" \
vendor/k8s.io/code-generator/generate-internal-groups.sh:105:-        --input-base "" \
vendor/k8s.io/code-generator/generate-internal-groups.sh:106:-        --input "$(codegen::join , "${APIS[@]}")" \
vendor/k8s.io/code-generator/generate-internal-groups.sh:107:-        --output-package "${OUTPUT_PKG}/${CLIENTSET_PKG_NAME:-clientset}" \
vendor/k8s.io/code-generator/generate-internal-groups.sh:108:-        "$@"
vendor/k8s.io/code-generator/generate-internal-groups.sh:109:-  fi
vendor/k8s.io/code-generator/generate-internal-groups.sh:110:-  "${GOPATH}/bin/client-gen" \
vendor/k8s.io/code-generator/generate-internal-groups.sh:111:-      --clientset-name "${CLIENTSET_NAME_VERSIONED:-versioned}" \
vendor/k8s.io/code-generator/generate-internal-groups.sh:108:+      --clientset-name "${CLIENTSET_NAME_INTERNAL:-internalversion}" \
2023-06-08T02:15:29.2247371Z ##[warning][shfmt] reported by reviewdog 🐶
```

**Review by ReToCode — APPROVED** [review]
/lgtm

**Pull request merged**
